services:
  app:
    build:
      context: .
    image: nextjs-portfolio-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./services
          target: /app/services
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
